const DEEZER_TOKEN_STORAGE_KEY = "dz";
const DEEZER_APP_ID = process.env.REACT_APP_DZ_APP_ID;
const BACKEND_URL = process.env.REACT_APP_BACKEND_URL || "";
const NUMBER_OF_RECOMMENDED_TRACKS = 100;
const NUMBER_OF_SEARCH_TRACKS = 100;

const config = {
  DEEZER_TOKEN_STORAGE_KEY,
  DEEZER_APP_ID,
  BACKEND_URL,
  NUMBER_OF_RECOMMENDED_TRACKS,
  NUMBER_OF_SEARCH_TRACKS,
};

export default config;
