const BACKEND_URL = process.env.REACT_APP_BACKEND_URL || "";
const NUMBER_OF_RECOMMENDED_TRACKS = 100;
const NUMBER_OF_SEARCH_TRACKS = 100;

const config = {
  BACKEND_URL,
  NUMBER_OF_RECOMMENDED_TRACKS,
  NUMBER_OF_SEARCH_TRACKS,
};

export default config;
